### ISSUE TITLE
Unknown content types should be ignored

### ISSUE THREAD

**Issue by bergos** [rdf-ext/rdf-body-parser#9]
There should be a check if there is a parser available for the content-type of the request. [Here](https://github.com/rdf-ext/rdf-body-parser/blob/master/index.js#L59) should be the check.

**Comment by pmcb55** [comment]
Maybe this simple test case might help!
Simply running this code with 'node test.js' generates a HTTP response code of 500 when hitting a standard Node Express server with 'rdf-body-parser' parsing the input:
```
var axios = require('axios')

const options = {
  headers: {
    'Content-Type': 'text/turtle',
    'Accept': 'application/json'
  },
  body: '_:b5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Event> .\n'
}

axios.post('http:<ENDPOINT>', options)
  .then((response) => {
    console.log(`SUCCESS: response: [${response}]`)
  })
  .catch((error) => {
    console.log(`EXCEPTION: ${error}, response data: [${error.response.data}]`)
  })
```

Response:
```
INNER EXCEPTION: Error: Request failed with status code 500, response data: [<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>Cannot read property 'once' of null</h1><h2></h2><pre>TypeError: Cannot read property 'once' of null
    at Promise (/usr/src/app/node_modules/rdf-dataset-simple/index.js:70:14)
    at new Promise (&lt;anonymous&gt;)
    at DatasetExt.import (/usr/src/app/node_modules/rdf-dataset-simple/index.js:69:12)
    at options.bodyParser (/usr/src/app/node_modules/rdf-body-parser/index.js:61:27)
    at Object.textParser [as bodyParser] (/usr/src/app/node_modules/body-parser/lib/types/text.js:60:7)
    at /usr/src/app/node_modules/rdf-body-parser/index.js:49:13
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/usr/src/app/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/usr/src/app/node_modules/cookie-parser/index.js:56:14)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)</pre></body></html>]
```

**Comment by ktk** [comment]
Replaced by https://github.com/rdfjs-base/express-handler
